import React from 'react';
import type { UserProfile } from '../features/auth/AuthContext';
import type { RoomSettings } from '../features/settings/types';
import { summariseRoomSettings, WIN_RULE_TEXT } from '../features/settings/types';
import type { LastRoom } from '../features/room/useRoom';
import { stagger } from './AppViewShared';

export interface HomeLobbyMetaProps { user: UserProfile | null; error: string | null; onDismissError: () => void; lastRoom: LastRoom | null; onRejoin: () => void; onDismissLast: () => void; settings: RoomSettings; onOpenRules: () => void; }
export const HomeLobbyMeta: React.FC<HomeLobbyMetaProps> = ({ user, error, onDismissError, lastRoom, onRejoin, onDismissLast, settings, onOpenRules }) => <><div className="home-lobby__intro flex flex-col items-center gap-3 pb-1 text-center"><h1 className="animate-pop-in" style={stagger(0)}><img src="/caro-cyberpunk-sword-slash.png" alt="" aria-hidden="true" className="mx-auto w-[min(82vw,430px)]" /><span className="sr-only">CARO - play Gomoku online</span></h1><p className="animate-pop-in mx-auto max-w-md text-muted" style={stagger(1)}>{WIN_RULE_TEXT}</p>{(!user || user.isGuest) && <p className="chip animate-pop-in" style={stagger(2)}>Play now, no account needed</p>}</div>{error && <div role="alert" className="home-lobby__notice flex flex-wrap items-center justify-between gap-2 rounded-md border border-danger bg-danger-soft p-3 text-xs font-medium text-danger"><span>{error}</span><button type="button" onClick={onDismissError} className="btn btn-secondary btn-sm">Dismiss</button></div>}{lastRoom && !error && <div role="status" className="home-lobby__notice flex flex-wrap items-center justify-between gap-2 rounded-md border border-line bg-surface p-3 text-sm"><span className="text-ink">You left room <span className="font-mono font-semibold text-accent-text">{lastRoom.roomId}</span>{lastRoom.hostName ? ` (${lastRoom.hostName}'s room)` : ''}.</span><span className="flex gap-2"><button type="button" onClick={onRejoin} className="btn btn-primary btn-sm">Rejoin</button><button type="button" onClick={onDismissLast} className="btn btn-ghost btn-sm">Dismiss</button></span></div>}<div className="home-lobby__rules card animate-pop-in flex flex-wrap items-center justify-between gap-3 p-4 text-left" style={stagger(5)}><div className="flex flex-wrap items-center gap-2">{summariseRoomSettings(settings).map((fact) => <span key={fact.label} className="chip"><span>{fact.label}</span><span className="font-semibold text-ink">{fact.value}</span></span>)}</div><button type="button" onClick={onOpenRules} className="btn btn-secondary btn-sm ml-auto shrink-0">Change rules</button></div></>;
